name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Changez 'main' par 'master' si votre branche par défaut s'appelle 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Utiliser Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Cela génère le dossier dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Répertoire à publier
